'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("rhMacros.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brick_link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick_link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bricks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bricks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;CodeCompletions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''  &lt;Entries&gt;
        '''    &lt;Entry&gt;
        '''      &lt;Code&gt;G0&lt;/Code&gt;
        '''      &lt;Description&gt;See G1&lt;/Description&gt;
        '''      &lt;IconId&gt;0&lt;/IconId&gt;
        '''    &lt;/Entry&gt;
        '''    &lt;Entry&gt;
        '''      &lt;Code&gt;G1&lt;/Code&gt;
        '''      &lt;Description&gt;Coordinated movement&lt;/Description&gt;
        '''      &lt;Parameters&gt;Xnnn Ynnn Znnn Ennn Fnnn&lt;/Parameters&gt;
        '''      &lt;IconId&gt;0&lt;/IconId&gt;
        '''    &lt;/Entry&gt;
        '''    &lt;Entry&gt;
        '''      &lt;Code&gt;G2&lt;/Code&gt;
        '''      &lt;Description&gt;ClockWise Arc&lt;/Descriptio [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CodeCompletion() As String
            Get
                Return ResourceManager.GetString("CodeCompletion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_brick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_brick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to adding.
        '''</summary>
        Friend ReadOnly Property MacrosUI_Command_Add() As String
            Get
                Return ResourceManager.GetString("MacrosUI_Command_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to deleting.
        '''</summary>
        Friend ReadOnly Property MacrosUI_Command_Delete() As String
            Get
                Return ResourceManager.GetString("MacrosUI_Command_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete this macro?.
        '''</summary>
        Friend ReadOnly Property MacrosUI_Command_Delete_Question() As String
            Get
                Return ResourceManager.GetString("MacrosUI_Command_Delete_Question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to editing.
        '''</summary>
        Friend ReadOnly Property MacrosUI_Command_Edit() As String
            Get
                Return ResourceManager.GetString("MacrosUI_Command_Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to executing.
        '''</summary>
        Friend ReadOnly Property MacrosUI_Command_Execute() As String
            Get
                Return ResourceManager.GetString("MacrosUI_Command_Execute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Something went wrong while {0} a macro..
        '''</summary>
        Friend ReadOnly Property MacrosUI_CommandErrorMessage_Template() As String
            Get
                Return ResourceManager.GetString("MacrosUI_CommandErrorMessage_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error {0} macro.
        '''</summary>
        Friend ReadOnly Property MacrosUI_CommandErrorTitle_Template() As String
            Get
                Return ResourceManager.GetString("MacrosUI_CommandErrorTitle_Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Something went wrong with the connection between Repetier Host and the plugin..
        '''</summary>
        Friend ReadOnly Property MacrosUi_Connect_Error_Message() As String
            Get
                Return ResourceManager.GetString("MacrosUi_Connect_Error_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error connecting.
        '''</summary>
        Friend ReadOnly Property MacrosUi_Connect_Error_Title() As String
            Get
                Return ResourceManager.GetString("MacrosUi_Connect_Error_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The rhMacros plugin path is not present in RepetierHost..
        '''</summary>
        Friend ReadOnly Property MacrosUi_Connect_PathNotFound_Message() As String
            Get
                Return ResourceManager.GetString("MacrosUi_Connect_PathNotFound_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path not found.
        '''</summary>
        Friend ReadOnly Property MacrosUi_Connect_PathNotFound_Title() As String
            Get
                Return ResourceManager.GetString("MacrosUi_Connect_PathNotFound_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Macro confirmation message.
        '''</summary>
        Friend ReadOnly Property MacrosUi_ExecuteMacro_Macro_confirmation_message_Title() As String
            Get
                Return ResourceManager.GetString("MacrosUi_ExecuteMacro_Macro_confirmation_message_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Something went wrong with loading the macro definition file..
        '''</summary>
        Friend ReadOnly Property MacrosUi_LoadMacroSets_Error_Message() As String
            Get
                Return ResourceManager.GetString("MacrosUi_LoadMacroSets_Error_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error loading definitions.
        '''</summary>
        Friend ReadOnly Property MacrosUi_LoadMacroSets_Error_Title() As String
            Get
                Return ResourceManager.GetString("MacrosUi_LoadMacroSets_Error_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Something went wrong with showing the macrobuttons..
        '''</summary>
        Friend ReadOnly Property MacrosUi_ShowMacroButtons_Error_Message() As String
            Get
                Return ResourceManager.GetString("MacrosUi_ShowMacroButtons_Error_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error showing macrobuttons.
        '''</summary>
        Friend ReadOnly Property MacrosUi_ShowMacroButtons_Error_Title() As String
            Get
                Return ResourceManager.GetString("MacrosUi_ShowMacroButtons_Error_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MenuBarBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuBarBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
